bashrc: fix syntax error

diff --git a/.bashrc.d/loader b/.bashrc.d/loader
--- a/.bashrc.d/loader
+++ b/.bashrc.d/loader
@@ -13,17 +13,18 @@ function __turenar_bashrc_loader() {
 
 	for dir in ${__turenar_bashrc_rcpath}; do
 		for i in "${dir}"/*_*; do
-		if ! test -x "$i"; then
-			printf "\033[KLoading %s..." "$i"
-			if source "$i"; then
-				printf " ok.\r"
-			else
-				echo " failed."
+			if ! test -x "$i"; then
+				printf "\033[KLoading %s..." "$i"
+				if source "$i"; then
+					printf " ok.\r"
+				else
+					echo " failed."
+				fi
 			fi
-		fi
+		done
 	done
 
-	printf "\033[K.bashrc loaded"
+	printf "\033[K.bashrc loaded\n"
 }
 
 if [[ $- = *i* ]]; then
